/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccusedDatabase {
  'id' : bigint,
  'ndpsQuantity' : string,
  'status' : AccusedStatus,
  'firDetails' : string,
  'seizureDetails' : string,
  'name' : string,
  'createdAt' : string,
  'policeStation' : string,
  'investigationRecords' : Array<InvestigationRecord>,
  'updatedAt' : string,
}
export type AccusedStatus = { 'absconded' : null } |
  { 'inJail' : null } |
  { 'onBail' : null };
export type ActivityType = { 'surveillance' : null } |
  { 'evidenceCollection' : null } |
  { 'arrest' : null } |
  { 'patrol' : null } |
  { 'witnessInterview' : null };
export interface Case {
  'id' : bigint,
  'status' : CaseStatus,
  'title' : string,
  'description' : string,
  'dateOpened' : string,
  'involvedOfficers' : Array<Principal>,
  'leadInvestigator' : Principal,
}
export type CaseStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'underInvestigation' : null } |
  { 'archived' : null };
export interface EvidenceItem {
  'id' : bigint,
  'status' : EvidenceStatus,
  'description' : string,
  'collectedBy' : Principal,
  'dateCollected' : string,
  'caseId' : bigint,
  'evidenceType' : { 'testimonial' : null } |
    { 'physical' : null } |
    { 'digital' : null },
}
export type EvidenceStatus = { 'inCustody' : null } |
  { 'analyzed' : null } |
  { 'returned' : null } |
  { 'destroyed' : null };
export type ExternalBlob = Uint8Array;
export interface InvestigationRecord {
  'id' : bigint,
  'title' : string,
  'createdAt' : string,
  'createdBy' : Principal,
  'description' : string,
  'attachments' : Array<ExternalBlob>,
}
export interface InvestigationTask {
  'id' : bigint,
  'status' : TaskStatus,
  'description' : string,
  'deadline' : string,
  'caseId' : bigint,
  'assignedOfficer' : Principal,
}
export interface OfficerActivityLog {
  'id' : bigint,
  'activityType' : ActivityType,
  'description' : string,
  'timestamp' : string,
  'officer' : Principal,
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'overdue' : null } |
  { 'inProgress' : null };
export interface UserProfile {
  'name' : string,
  'rank' : string,
  'department' : string,
  'badgeNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEvidenceItem' : ActorMethod<
    [
      bigint,
      string,
      string,
      { 'testimonial' : null } |
        { 'physical' : null } |
        { 'digital' : null },
    ],
    bigint
  >,
  'addInvestigationRecordToAccused' : ActorMethod<
    [bigint, string, string, [] | [Array<ExternalBlob>]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccused' : ActorMethod<
    [string, AccusedStatus, string, string, string, string],
    bigint
  >,
  'createCase' : ActorMethod<[string, string, Principal, string], bigint>,
  'createInvestigationTask' : ActorMethod<
    [bigint, string, Principal, string],
    bigint
  >,
  'getAccusedRecord' : ActorMethod<[bigint], [] | [AccusedDatabase]>,
  'getAccusedRecordsByStatus' : ActorMethod<
    [AccusedStatus],
    Array<AccusedDatabase>
  >,
  'getAllAccusedRecords' : ActorMethod<[], Array<AccusedDatabase>>,
  'getAllCases' : ActorMethod<[], Array<Case>>,
  'getAllEvidenceItems' : ActorMethod<[], Array<EvidenceItem>>,
  'getAllInvestigationTasks' : ActorMethod<[], Array<InvestigationTask>>,
  'getAllOfficerActivityLogs' : ActorMethod<[], Array<OfficerActivityLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCase' : ActorMethod<[bigint], [] | [Case]>,
  'getEvidenceItem' : ActorMethod<[bigint], [] | [EvidenceItem]>,
  'getInvestigationTask' : ActorMethod<[bigint], [] | [InvestigationTask]>,
  'getOfficerActivityLog' : ActorMethod<[bigint], [] | [OfficerActivityLog]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logOfficerActivity' : ActorMethod<[ActivityType, string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchAccusedRecords' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [AccusedStatus]],
    Array<AccusedDatabase>
  >,
  'updateAccused' : ActorMethod<
    [bigint, string, AccusedStatus, string, string, string, string],
    undefined
  >,
  'updateCaseStatus' : ActorMethod<[bigint, CaseStatus], undefined>,
  'updateEvidenceStatus' : ActorMethod<[bigint, EvidenceStatus], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];