/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccusedStatus = IDL.Variant({
  'absconded' : IDL.Null,
  'inJail' : IDL.Null,
  'onBail' : IDL.Null,
});
export const InvestigationRecord = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'attachments' : IDL.Vec(ExternalBlob),
});
export const AccusedDatabase = IDL.Record({
  'id' : IDL.Nat,
  'ndpsQuantity' : IDL.Text,
  'status' : AccusedStatus,
  'firDetails' : IDL.Text,
  'seizureDetails' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'policeStation' : IDL.Text,
  'investigationRecords' : IDL.Vec(InvestigationRecord),
  'updatedAt' : IDL.Text,
});
export const CaseStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'underInvestigation' : IDL.Null,
  'archived' : IDL.Null,
});
export const Case = IDL.Record({
  'id' : IDL.Nat,
  'status' : CaseStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'dateOpened' : IDL.Text,
  'involvedOfficers' : IDL.Vec(IDL.Principal),
  'leadInvestigator' : IDL.Principal,
});
export const EvidenceStatus = IDL.Variant({
  'inCustody' : IDL.Null,
  'analyzed' : IDL.Null,
  'returned' : IDL.Null,
  'destroyed' : IDL.Null,
});
export const EvidenceItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : EvidenceStatus,
  'description' : IDL.Text,
  'collectedBy' : IDL.Principal,
  'dateCollected' : IDL.Text,
  'caseId' : IDL.Nat,
  'evidenceType' : IDL.Variant({
    'testimonial' : IDL.Null,
    'physical' : IDL.Null,
    'digital' : IDL.Null,
  }),
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'overdue' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const InvestigationTask = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'caseId' : IDL.Nat,
  'assignedOfficer' : IDL.Principal,
});
export const ActivityType = IDL.Variant({
  'surveillance' : IDL.Null,
  'evidenceCollection' : IDL.Null,
  'arrest' : IDL.Null,
  'patrol' : IDL.Null,
  'witnessInterview' : IDL.Null,
});
export const OfficerActivityLog = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : ActivityType,
  'description' : IDL.Text,
  'timestamp' : IDL.Text,
  'officer' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'rank' : IDL.Text,
  'department' : IDL.Text,
  'badgeNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEvidenceItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'testimonial' : IDL.Null,
          'physical' : IDL.Null,
          'digital' : IDL.Null,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'addInvestigationRecordToAccused' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(ExternalBlob))],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAccused' : IDL.Func(
      [IDL.Text, AccusedStatus, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createCase' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createInvestigationTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Principal, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAccusedRecord' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(AccusedDatabase)],
      ['query'],
    ),
  'getAccusedRecordsByStatus' : IDL.Func(
      [AccusedStatus],
      [IDL.Vec(AccusedDatabase)],
      ['query'],
    ),
  'getAllAccusedRecords' : IDL.Func([], [IDL.Vec(AccusedDatabase)], ['query']),
  'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getAllEvidenceItems' : IDL.Func([], [IDL.Vec(EvidenceItem)], ['query']),
  'getAllInvestigationTasks' : IDL.Func(
      [],
      [IDL.Vec(InvestigationTask)],
      ['query'],
    ),
  'getAllOfficerActivityLogs' : IDL.Func(
      [],
      [IDL.Vec(OfficerActivityLog)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCase' : IDL.Func([IDL.Nat], [IDL.Opt(Case)], ['query']),
  'getEvidenceItem' : IDL.Func([IDL.Nat], [IDL.Opt(EvidenceItem)], ['query']),
  'getInvestigationTask' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(InvestigationTask)],
      ['query'],
    ),
  'getOfficerActivityLog' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(OfficerActivityLog)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logOfficerActivity' : IDL.Func(
      [ActivityType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAccusedRecords' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(AccusedStatus),
      ],
      [IDL.Vec(AccusedDatabase)],
      ['query'],
    ),
  'updateAccused' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        AccusedStatus,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateCaseStatus' : IDL.Func([IDL.Nat, CaseStatus], [], []),
  'updateEvidenceStatus' : IDL.Func([IDL.Nat, EvidenceStatus], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccusedStatus = IDL.Variant({
    'absconded' : IDL.Null,
    'inJail' : IDL.Null,
    'onBail' : IDL.Null,
  });
  const InvestigationRecord = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'attachments' : IDL.Vec(ExternalBlob),
  });
  const AccusedDatabase = IDL.Record({
    'id' : IDL.Nat,
    'ndpsQuantity' : IDL.Text,
    'status' : AccusedStatus,
    'firDetails' : IDL.Text,
    'seizureDetails' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'policeStation' : IDL.Text,
    'investigationRecords' : IDL.Vec(InvestigationRecord),
    'updatedAt' : IDL.Text,
  });
  const CaseStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'underInvestigation' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Case = IDL.Record({
    'id' : IDL.Nat,
    'status' : CaseStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'dateOpened' : IDL.Text,
    'involvedOfficers' : IDL.Vec(IDL.Principal),
    'leadInvestigator' : IDL.Principal,
  });
  const EvidenceStatus = IDL.Variant({
    'inCustody' : IDL.Null,
    'analyzed' : IDL.Null,
    'returned' : IDL.Null,
    'destroyed' : IDL.Null,
  });
  const EvidenceItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : EvidenceStatus,
    'description' : IDL.Text,
    'collectedBy' : IDL.Principal,
    'dateCollected' : IDL.Text,
    'caseId' : IDL.Nat,
    'evidenceType' : IDL.Variant({
      'testimonial' : IDL.Null,
      'physical' : IDL.Null,
      'digital' : IDL.Null,
    }),
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'overdue' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const InvestigationTask = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'caseId' : IDL.Nat,
    'assignedOfficer' : IDL.Principal,
  });
  const ActivityType = IDL.Variant({
    'surveillance' : IDL.Null,
    'evidenceCollection' : IDL.Null,
    'arrest' : IDL.Null,
    'patrol' : IDL.Null,
    'witnessInterview' : IDL.Null,
  });
  const OfficerActivityLog = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : ActivityType,
    'description' : IDL.Text,
    'timestamp' : IDL.Text,
    'officer' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'rank' : IDL.Text,
    'department' : IDL.Text,
    'badgeNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEvidenceItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'testimonial' : IDL.Null,
            'physical' : IDL.Null,
            'digital' : IDL.Null,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'addInvestigationRecordToAccused' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(ExternalBlob))],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAccused' : IDL.Func(
        [IDL.Text, AccusedStatus, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createCase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createInvestigationTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Principal, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAccusedRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AccusedDatabase)],
        ['query'],
      ),
    'getAccusedRecordsByStatus' : IDL.Func(
        [AccusedStatus],
        [IDL.Vec(AccusedDatabase)],
        ['query'],
      ),
    'getAllAccusedRecords' : IDL.Func(
        [],
        [IDL.Vec(AccusedDatabase)],
        ['query'],
      ),
    'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getAllEvidenceItems' : IDL.Func([], [IDL.Vec(EvidenceItem)], ['query']),
    'getAllInvestigationTasks' : IDL.Func(
        [],
        [IDL.Vec(InvestigationTask)],
        ['query'],
      ),
    'getAllOfficerActivityLogs' : IDL.Func(
        [],
        [IDL.Vec(OfficerActivityLog)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCase' : IDL.Func([IDL.Nat], [IDL.Opt(Case)], ['query']),
    'getEvidenceItem' : IDL.Func([IDL.Nat], [IDL.Opt(EvidenceItem)], ['query']),
    'getInvestigationTask' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InvestigationTask)],
        ['query'],
      ),
    'getOfficerActivityLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(OfficerActivityLog)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logOfficerActivity' : IDL.Func(
        [ActivityType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAccusedRecords' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(AccusedStatus),
        ],
        [IDL.Vec(AccusedDatabase)],
        ['query'],
      ),
    'updateAccused' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          AccusedStatus,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateCaseStatus' : IDL.Func([IDL.Nat, CaseStatus], [], []),
    'updateEvidenceStatus' : IDL.Func([IDL.Nat, EvidenceStatus], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };