/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface InvestigationRecord {
    id: bigint;
    title: string;
    createdAt: string;
    createdBy: Principal;
    description: string;
    attachments: Array<ExternalBlob>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface InvestigationTask {
    id: bigint;
    status: TaskStatus;
    description: string;
    deadline: string;
    caseId: bigint;
    assignedOfficer: Principal;
}
export interface AccusedDatabase {
    id: bigint;
    ndpsQuantity: string;
    status: AccusedStatus;
    firDetails: string;
    seizureDetails: string;
    name: string;
    createdAt: string;
    policeStation: string;
    investigationRecords: Array<InvestigationRecord>;
    updatedAt: string;
}
export interface OfficerActivityLog {
    id: bigint;
    activityType: ActivityType;
    description: string;
    timestamp: string;
    officer: Principal;
}
export interface EvidenceItem {
    id: bigint;
    status: EvidenceStatus;
    description: string;
    collectedBy: Principal;
    dateCollected: string;
    caseId: bigint;
    evidenceType: Variant_testimonial_physical_digital;
}
export interface Case {
    id: bigint;
    status: CaseStatus;
    title: string;
    description: string;
    dateOpened: string;
    involvedOfficers: Array<Principal>;
    leadInvestigator: Principal;
}
export interface UserProfile {
    name: string;
    rank: string;
    department: string;
    badgeNumber: string;
}
export enum AccusedStatus {
    absconded = "absconded",
    inJail = "inJail",
    onBail = "onBail"
}
export enum ActivityType {
    surveillance = "surveillance",
    evidenceCollection = "evidenceCollection",
    arrest = "arrest",
    patrol = "patrol",
    witnessInterview = "witnessInterview"
}
export enum CaseStatus {
    closed = "closed",
    open = "open",
    underInvestigation = "underInvestigation",
    archived = "archived"
}
export enum EvidenceStatus {
    inCustody = "inCustody",
    analyzed = "analyzed",
    returned = "returned",
    destroyed = "destroyed"
}
export enum TaskStatus {
    pending = "pending",
    completed = "completed",
    overdue = "overdue",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_testimonial_physical_digital {
    testimonial = "testimonial",
    physical = "physical",
    digital = "digital"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEvidenceItem(caseId: bigint, description: string, dateCollected: string, evidenceType: Variant_testimonial_physical_digital): Promise<bigint>;
    addInvestigationRecordToAccused(accusedId: bigint, title: string, description: string, attachments: Array<ExternalBlob> | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAccused(name: string, status: AccusedStatus, firDetails: string, seizureDetails: string, ndpsQuantity: string, policeStation: string): Promise<bigint>;
    createCase(title: string, description: string, leadInvestigator: Principal, dateOpened: string): Promise<bigint>;
    createInvestigationTask(caseId: bigint, description: string, assignedOfficer: Principal, deadline: string): Promise<bigint>;
    getAccusedRecord(accusedId: bigint): Promise<AccusedDatabase | null>;
    getAccusedRecordsByStatus(status: AccusedStatus): Promise<Array<AccusedDatabase>>;
    getAllAccusedRecords(): Promise<Array<AccusedDatabase>>;
    getAllCases(): Promise<Array<Case>>;
    getAllEvidenceItems(): Promise<Array<EvidenceItem>>;
    getAllInvestigationTasks(): Promise<Array<InvestigationTask>>;
    getAllOfficerActivityLogs(): Promise<Array<OfficerActivityLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCase(caseId: bigint): Promise<Case | null>;
    getEvidenceItem(evidenceId: bigint): Promise<EvidenceItem | null>;
    getInvestigationTask(taskId: bigint): Promise<InvestigationTask | null>;
    getOfficerActivityLog(logId: bigint): Promise<OfficerActivityLog | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logOfficerActivity(activityType: ActivityType, description: string, timestamp: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchAccusedRecords(nameQuery: string | null, firQuery: string | null, policeStationQuery: string | null, statusFilter: AccusedStatus | null): Promise<Array<AccusedDatabase>>;
    updateAccused(accusedId: bigint, name: string, status: AccusedStatus, firDetails: string, seizureDetails: string, ndpsQuantity: string, policeStation: string): Promise<void>;
    updateCaseStatus(caseId: bigint, status: CaseStatus): Promise<void>;
    updateEvidenceStatus(evidenceId: bigint, status: EvidenceStatus): Promise<void>;
    updateTaskStatus(taskId: bigint, status: TaskStatus): Promise<void>;
}
import type { AccusedDatabase as _AccusedDatabase, AccusedStatus as _AccusedStatus, ActivityType as _ActivityType, Case as _Case, CaseStatus as _CaseStatus, EvidenceItem as _EvidenceItem, EvidenceStatus as _EvidenceStatus, ExternalBlob as _ExternalBlob, InvestigationRecord as _InvestigationRecord, InvestigationTask as _InvestigationTask, OfficerActivityLog as _OfficerActivityLog, TaskStatus as _TaskStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEvidenceItem(arg0: bigint, arg1: string, arg2: string, arg3: Variant_testimonial_physical_digital): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvidenceItem(arg0, arg1, arg2, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvidenceItem(arg0, arg1, arg2, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addInvestigationRecordToAccused(arg0: bigint, arg1: string, arg2: string, arg3: Array<ExternalBlob> | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvestigationRecordToAccused(arg0, arg1, arg2, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvestigationRecordToAccused(arg0, arg1, arg2, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAccused(arg0: string, arg1: AccusedStatus, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAccused(arg0, to_candid_AccusedStatus_n14(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAccused(arg0, to_candid_AccusedStatus_n14(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createCase(arg0: string, arg1: string, arg2: Principal, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCase(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCase(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createInvestigationTask(arg0: bigint, arg1: string, arg2: Principal, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvestigationTask(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvestigationTask(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAccusedRecord(arg0: bigint): Promise<AccusedDatabase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccusedRecord(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccusedRecord(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccusedRecordsByStatus(arg0: AccusedStatus): Promise<Array<AccusedDatabase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccusedRecordsByStatus(to_candid_AccusedStatus_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccusedRecordsByStatus(to_candid_AccusedStatus_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAccusedRecords(): Promise<Array<AccusedDatabase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAccusedRecords();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAccusedRecords();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCases();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCases();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvidenceItems(): Promise<Array<EvidenceItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvidenceItems();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvidenceItems();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInvestigationTasks(): Promise<Array<InvestigationTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvestigationTasks();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvestigationTasks();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOfficerActivityLogs(): Promise<Array<OfficerActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOfficerActivityLogs();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOfficerActivityLogs();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCase(arg0: bigint): Promise<Case | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCase(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCase(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvidenceItem(arg0: bigint): Promise<EvidenceItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvidenceItem(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvidenceItem(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestigationTask(arg0: bigint): Promise<InvestigationTask | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestigationTask(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestigationTask(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfficerActivityLog(arg0: bigint): Promise<OfficerActivityLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficerActivityLog(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficerActivityLog(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logOfficerActivity(arg0: ActivityType, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logOfficerActivity(to_candid_ActivityType_n55(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logOfficerActivity(to_candid_ActivityType_n55(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchAccusedRecords(arg0: string | null, arg1: string | null, arg2: string | null, arg3: AccusedStatus | null): Promise<Array<AccusedDatabase>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAccusedRecords(to_candid_opt_n57(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n57(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n57(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n58(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAccusedRecords(to_candid_opt_n57(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n57(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n57(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n58(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAccused(arg0: bigint, arg1: string, arg2: AccusedStatus, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccused(arg0, arg1, to_candid_AccusedStatus_n14(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccused(arg0, arg1, to_candid_AccusedStatus_n14(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateCaseStatus(arg0: bigint, arg1: CaseStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaseStatus(arg0, to_candid_CaseStatus_n59(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaseStatus(arg0, to_candid_CaseStatus_n59(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEvidenceStatus(arg0: bigint, arg1: EvidenceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvidenceStatus(arg0, to_candid_EvidenceStatus_n61(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvidenceStatus(arg0, to_candid_EvidenceStatus_n61(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaskStatus(arg0: bigint, arg1: TaskStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n63(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n63(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_AccusedDatabase_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccusedDatabase): Promise<AccusedDatabase> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_AccusedStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccusedStatus): AccusedStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_CaseStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseStatus): CaseStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Case_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Case): Case {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_EvidenceItem_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvidenceItem): EvidenceItem {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_EvidenceStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvidenceStatus): EvidenceStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_InvestigationRecord_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestigationRecord): Promise<InvestigationRecord> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_InvestigationTask_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestigationTask): InvestigationTask {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_OfficerActivityLog_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfficerActivityLog): OfficerActivityLog {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccusedDatabase]): Promise<AccusedDatabase | null> {
    return value.length === 0 ? null : await from_candid_AccusedDatabase_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Case]): Case | null {
    return value.length === 0 ? null : from_candid_Case_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EvidenceItem]): EvidenceItem | null {
    return value.length === 0 ? null : from_candid_EvidenceItem_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvestigationTask]): InvestigationTask | null {
    return value.length === 0 ? null : from_candid_InvestigationTask_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OfficerActivityLog]): OfficerActivityLog | null {
    return value.length === 0 ? null : from_candid_OfficerActivityLog_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ndpsQuantity: string;
    status: _AccusedStatus;
    firDetails: string;
    seizureDetails: string;
    name: string;
    createdAt: string;
    policeStation: string;
    investigationRecords: Array<_InvestigationRecord>;
    updatedAt: string;
}): Promise<{
    id: bigint;
    ndpsQuantity: string;
    status: AccusedStatus;
    firDetails: string;
    seizureDetails: string;
    name: string;
    createdAt: string;
    policeStation: string;
    investigationRecords: Array<InvestigationRecord>;
    updatedAt: string;
}> {
    return {
        id: value.id,
        ndpsQuantity: value.ndpsQuantity,
        status: from_candid_AccusedStatus_n19(_uploadFile, _downloadFile, value.status),
        firDetails: value.firDetails,
        seizureDetails: value.seizureDetails,
        name: value.name,
        createdAt: value.createdAt,
        policeStation: value.policeStation,
        investigationRecords: await from_candid_vec_n21(_uploadFile, _downloadFile, value.investigationRecords),
        updatedAt: value.updatedAt
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    createdAt: string;
    createdBy: Principal;
    description: string;
    attachments: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    title: string;
    createdAt: string;
    createdBy: Principal;
    description: string;
    attachments: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        attachments: await from_candid_vec_n24(_uploadFile, _downloadFile, value.attachments)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CaseStatus;
    title: string;
    description: string;
    dateOpened: string;
    involvedOfficers: Array<Principal>;
    leadInvestigator: Principal;
}): {
    id: bigint;
    status: CaseStatus;
    title: string;
    description: string;
    dateOpened: string;
    involvedOfficers: Array<Principal>;
    leadInvestigator: Principal;
} {
    return {
        id: value.id,
        status: from_candid_CaseStatus_n30(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        dateOpened: value.dateOpened,
        involvedOfficers: value.involvedOfficers,
        leadInvestigator: value.leadInvestigator
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EvidenceStatus;
    description: string;
    collectedBy: Principal;
    dateCollected: string;
    caseId: bigint;
    evidenceType: {
        testimonial: null;
    } | {
        physical: null;
    } | {
        digital: null;
    };
}): {
    id: bigint;
    status: EvidenceStatus;
    description: string;
    collectedBy: Principal;
    dateCollected: string;
    caseId: bigint;
    evidenceType: Variant_testimonial_physical_digital;
} {
    return {
        id: value.id,
        status: from_candid_EvidenceStatus_n35(_uploadFile, _downloadFile, value.status),
        description: value.description,
        collectedBy: value.collectedBy,
        dateCollected: value.dateCollected,
        caseId: value.caseId,
        evidenceType: from_candid_variant_n37(_uploadFile, _downloadFile, value.evidenceType)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    description: string;
    deadline: string;
    caseId: bigint;
    assignedOfficer: Principal;
}): {
    id: bigint;
    status: TaskStatus;
    description: string;
    deadline: string;
    caseId: bigint;
    assignedOfficer: Principal;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n41(_uploadFile, _downloadFile, value.status),
        description: value.description,
        deadline: value.deadline,
        caseId: value.caseId,
        assignedOfficer: value.assignedOfficer
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    activityType: _ActivityType;
    description: string;
    timestamp: string;
    officer: Principal;
}): {
    id: bigint;
    activityType: ActivityType;
    description: string;
    timestamp: string;
    officer: Principal;
} {
    return {
        id: value.id,
        activityType: from_candid_ActivityType_n46(_uploadFile, _downloadFile, value.activityType),
        description: value.description,
        timestamp: value.timestamp,
        officer: value.officer
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    absconded: null;
} | {
    inJail: null;
} | {
    onBail: null;
}): AccusedStatus {
    return "absconded" in value ? AccusedStatus.absconded : "inJail" in value ? AccusedStatus.inJail : "onBail" in value ? AccusedStatus.onBail : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    underInvestigation: null;
} | {
    archived: null;
}): CaseStatus {
    return "closed" in value ? CaseStatus.closed : "open" in value ? CaseStatus.open : "underInvestigation" in value ? CaseStatus.underInvestigation : "archived" in value ? CaseStatus.archived : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inCustody: null;
} | {
    analyzed: null;
} | {
    returned: null;
} | {
    destroyed: null;
}): EvidenceStatus {
    return "inCustody" in value ? EvidenceStatus.inCustody : "analyzed" in value ? EvidenceStatus.analyzed : "returned" in value ? EvidenceStatus.returned : "destroyed" in value ? EvidenceStatus.destroyed : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    testimonial: null;
} | {
    physical: null;
} | {
    digital: null;
}): Variant_testimonial_physical_digital {
    return "testimonial" in value ? Variant_testimonial_physical_digital.testimonial : "physical" in value ? Variant_testimonial_physical_digital.physical : "digital" in value ? Variant_testimonial_physical_digital.digital : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    overdue: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "completed" in value ? TaskStatus.completed : "overdue" in value ? TaskStatus.overdue : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    surveillance: null;
} | {
    evidenceCollection: null;
} | {
    arrest: null;
} | {
    patrol: null;
} | {
    witnessInterview: null;
}): ActivityType {
    return "surveillance" in value ? ActivityType.surveillance : "evidenceCollection" in value ? ActivityType.evidenceCollection : "arrest" in value ? ActivityType.arrest : "patrol" in value ? ActivityType.patrol : "witnessInterview" in value ? ActivityType.witnessInterview : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvestigationRecord>): Promise<Array<InvestigationRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_InvestigationRecord_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AccusedDatabase>): Promise<Array<AccusedDatabase>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AccusedDatabase_n17(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Case>): Array<Case> {
    return value.map((x)=>from_candid_Case_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EvidenceItem>): Array<EvidenceItem> {
    return value.map((x)=>from_candid_EvidenceItem_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvestigationTask>): Array<InvestigationTask> {
    return value.map((x)=>from_candid_InvestigationTask_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OfficerActivityLog>): Array<OfficerActivityLog> {
    return value.map((x)=>from_candid_OfficerActivityLog_n44(_uploadFile, _downloadFile, x));
}
function to_candid_AccusedStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccusedStatus): _AccusedStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ActivityType_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_CaseStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): _CaseStatus {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_EvidenceStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EvidenceStatus): _EvidenceStatus {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_TaskStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccusedStatus | null): [] | [_AccusedStatus] {
    return value === null ? candid_none() : candid_some(to_candid_AccusedStatus_n14(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob> | null): Promise<[] | [Array<_ExternalBlob>]> {
    return value === null ? candid_none() : candid_some(await to_candid_vec_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccusedStatus): {
    absconded: null;
} | {
    inJail: null;
} | {
    onBail: null;
} {
    return value == AccusedStatus.absconded ? {
        absconded: null
    } : value == AccusedStatus.inJail ? {
        inJail: null
    } : value == AccusedStatus.onBail ? {
        onBail: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    surveillance: null;
} | {
    evidenceCollection: null;
} | {
    arrest: null;
} | {
    patrol: null;
} | {
    witnessInterview: null;
} {
    return value == ActivityType.surveillance ? {
        surveillance: null
    } : value == ActivityType.evidenceCollection ? {
        evidenceCollection: null
    } : value == ActivityType.arrest ? {
        arrest: null
    } : value == ActivityType.patrol ? {
        patrol: null
    } : value == ActivityType.witnessInterview ? {
        witnessInterview: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): {
    closed: null;
} | {
    open: null;
} | {
    underInvestigation: null;
} | {
    archived: null;
} {
    return value == CaseStatus.closed ? {
        closed: null
    } : value == CaseStatus.open ? {
        open: null
    } : value == CaseStatus.underInvestigation ? {
        underInvestigation: null
    } : value == CaseStatus.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EvidenceStatus): {
    inCustody: null;
} | {
    analyzed: null;
} | {
    returned: null;
} | {
    destroyed: null;
} {
    return value == EvidenceStatus.inCustody ? {
        inCustody: null
    } : value == EvidenceStatus.analyzed ? {
        analyzed: null
    } : value == EvidenceStatus.returned ? {
        returned: null
    } : value == EvidenceStatus.destroyed ? {
        destroyed: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    pending: null;
} | {
    completed: null;
} | {
    overdue: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.pending ? {
        pending: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.overdue ? {
        overdue: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_testimonial_physical_digital): {
    testimonial: null;
} | {
    physical: null;
} | {
    digital: null;
} {
    return value == Variant_testimonial_physical_digital.testimonial ? {
        testimonial: null
    } : value == Variant_testimonial_physical_digital.physical ? {
        physical: null
    } : value == Variant_testimonial_physical_digital.digital ? {
        digital: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
